### ISSUE TITLE
Studentovi projekty

### ISSUE THREAD

**Issue by pavlosweb** [pavlosweb/lerhrgktlm#45]
Po přihlášení studenta by se měl zobrazit seznam jeho projektů.

**Comment by mec060** [comment]
tady je záludný dotaz jak ze sebe udělám pouze student jinak seznam projektu asi funguje

**Comment by pavlosweb** [comment]
v global.asax se přiřazují role.

**Comment by mec060** [comment]
taky vypadá v pořádky a taky bych možná po přihlášení studenta přešel rovnou na seznam jeho projektů

**Comment by pavlosweb** [comment]
stejné jak projectlist. nebudeme to řešit. od příštího roku to bude součást dbedu
