### ISSUE TITLE
Pamatování vybraných hodnot v DropDownListech

### ISSUE THREAD

**Issue by pavlosweb** [pavlosweb/lerhrgktlm#48]
Na stránce projectList.aspx se do session se ukládají hodnoty vybrané v drop down listu: cvičící a ročník.

**Comment by mec060** [comment]
Tady je otázka jak by to mělo být konzistentní někdy se hodnoty mažou někdy ignorují je to takové zajímavé hlavně když se do toho přidá ten filtr podle loginu nebo stavu

**Comment by pavlosweb** [comment]
zatím je to na 2 skupiny. buď fitruješ podle dropdownlistů nebo podle loginu studenta

**Comment by mec060** [comment]
V tom případě to vypadá v pořádku i když bych spíš čekal že to budeš moct kombinovat všechny volby

**Comment by pavlosweb** [comment]
Cvičící vidí jen svoje projekty, pro něj je důležité najít kontrétního studenta nebo filtrovat projekty podle stavu. Kombinace stavu projektu s loginem nemá smysl. Buď potřebuješ nebo druhé.
