### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by pavlosweb** [pavlosweb/lerhrgktlm#5]
Logovat důležité eventy.
Místo throw new AplicationException zobrazit chybovou hlášku.

**Comment by mec060** [comment]
ok vypadá že se loguje jen pro info co všechno se má logovat?

**Comment by pavlosweb** [comment]
idealně všechno důležité. Aktuálně to je vyhodnocení projektu a uzavření projektu. Odesílání emailů má samostatný log.

**Comment by mec060** [comment]
No ještě se tam loguje požadavek na zobrazení např. 
04.01. 18:42:27	Info	Request for VIEW project with key: NtI81+Ca7czYiM6h75y+/xFgx3OEt7imx97RAofrRD/yYbwrvio4oNDn23zfBQCBBCqJGeiUDhawGTlS9PqfRQ==

**Comment by pavlosweb** [comment]
To tam je zatím jen pro debug, časem to zredukujeme. Tenhle záznam se vytvoří pokud někdo otevře odkaz z emailu.

**Comment by mec060** [comment]
ok v tom případě to vypadá v pořádku
